### ISSUE TITLE
OpenCode in social media section

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/opencode2017#107]
By using the twitter api,add a section in the webpage which shows all the posts with the "#opencode" and "#geekhaveniiita".
(This is my contribution towards issue no.(#58))

**Comment by VamsiSangam** [comment]
Will work on this. I've done some reading, I'm not sure if this can be done. Will keep digging

**Comment by gauthamzz** [comment]
yeah im also not sure :/ i guess we need to close this issue . we can rather use twitter api and show tweets thats it
