### ISSUE TITLE
Make your own personal page- For Everyone

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#108]
Create your own personal page at `your_github-username.github.io`  and post in the comment and send a pr updating your data in `students.yml`

**Comment by VamsiSangam** [comment]
[vamsisangam.github.io](https://vamsisangam.github.io/) . What would the new attribute in ```students.yml``` be? ```blog``` perhaps?

**Comment by gauthamzz** [comment]
yeah that would be enough @VamsiSangam

**Comment by VamsiSangam** [comment]
Wouldn't it be ```username.github.io``` for everyone? What benefit do we get from storing it separately?

**Comment by gauthamzz** [comment]
well , not all people will make it .

**Comment by aswinzz** [comment]
Personal Page Created :+1:  https://aswinzz.github.io
Students.yml Updated

**Comment by RavicharanN** [comment]
https://ravicharann.github.io

**Comment by aswanthkoleri** [comment]
https://aswanthkoleri.github.io

**Comment by Anupam-dagar** [comment]
https://anupam-dagar.github.io/
Forgive the design,not able to host my site properly.Don't know where I am going wrong.
