### ISSUE TITLE
Change cards

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#113]
The cards that are used to display student and mentor names as pretty basic.
We would like to display them in a much better fashion and effect if possible. 

You can suggest your ideas and proceed forward

**Comment by anu-007** [comment]
what about this  http://codepen.io/nicotinell/pen/doXyVX

**Comment by gauthamzz** [comment]
Its almost same, something better i would propose

**Comment by anu-007** [comment]
will this work ?     http://codepen.io/marlenesco/pen/NqOozj

**Comment by gauthamzz** [comment]
yeah it looks good :+1:

**Comment by anu-007** [comment]
ok I will send a PR by tomorrow.

**Comment by gauthamzz** [comment]
@anu-007 how this going ? any issues ?

**Comment by anu-007** [comment]
just a little bit of work is remaining,i will send a PR shortly.

**Comment by gauthamzz** [comment]
@anu-007 if you are facing any problem you can come on the gitter channel and ask us

**Comment by anu-007** [comment]
@gauthamzz chek it out ( https://anu-007.github.io/opencodecollab/  ) just a little bit of work is left.
 I want your review on the new cards will these work or should change them.

**Comment by gauthamzz** [comment]
@anu-007 i don't think they should overlap , but what about the one you showed me earlier ?

**Comment by anu-007** [comment]
I faced a lot of difficulty in the animations of previous design so I decided to work on a different design. Can you explain more about the problem with this design.

**Comment by gauthamzz** [comment]
@anu-007 i would prefer if we go with the old design , this doesnt look that great . You can come on gitter and we can help you out . On the problems you are facing

**Comment by itaditya** [comment]
Can I take this issue ?

**Comment by gauthamzz** [comment]
yeah sure 
there is a pr in this issue already you can check it out 
you can either fix that :) or do yours
the event will be over on 17 please send pr asap

**Comment by itaditya** [comment]
I want to make a separate PR , I wanted to know do you like this card http://bootsnipp.com/snippets/featured/profile-card

**Comment by gauthamzz** [comment]
i think the current one looks better than this ?

**Comment by itaditya** [comment]
What about this one - http://codepen.io/VictoryDesign/pen/PqQevB

**Comment by gauthamzz** [comment]
i dont think its gonna matter much after we change the background .
something else ?
