### ISSUE TITLE
Fix the Opencode trailer.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/opencode2017#119]
Audio of the trailer still continue to play if the trailer is closed before watching completely.
(This is my contribution towards issue no.(#58))

**Comment by aswinzz** [comment]
i will work on this

**Comment by gauthamzz** [comment]
@aswinzz okay , just make sure you create different pr for both

**Comment by gauthamzz** [comment]
@aswinzz whats the progress on this :small_airplane:

**Comment by aswinzz** [comment]
its done
going to make pr
