### ISSUE TITLE
Enable gh-pages on your fork

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#15]
enable gh-pages on your fork in settings. please comment the link in this thread to earn points.

**Comment by bhanu1911** [comment]
https://bhanu1911.github.io/opencodecollab Will this do, sir?

**Comment by gauthamzz** [comment]
:+1: LGTM

**Comment by Symphoria** [comment]
Enabled **Github Pages** ,link - [https://symphoria.github.io/opencodecollab/](url)

**Comment by Ellusionists** [comment]
Enabled gh-pages.
Link :[https://ellusionists.github.io/opencodecollab/]

**Comment by VamsiSangam** [comment]
Could you please help me with this issue? I seem to be stuck. I did activate gh-pages for my fork and it says my site is published at [https://vamsisangam.github.io/opencodecollab/](https://vamsisangam.github.io/opencodecollab/), but when I open that link I am getting a "Site not found".

**Comment by VamsiSangam** [comment]
![capture](https://cloud.githubusercontent.com/assets/11662001/22036830/dc5272b0-dd1a-11e6-8e54-ef67db17b9cb.JPG)
 Need help with this.

**Comment by gauthamzz** [comment]
Might be some server error . You can refresh it . If it still persists please syc with the master branch

**Comment by VamsiSangam** [comment]
Okay. I already have [https://vamsisangam.github.io/](https://vamsisangam.github.io/) running, could it because of that? Does github allow us to use gh-pages on multiple repos?

**Comment by gauthamzz** [comment]
Yeah they allow , that's not a problem .

**Comment by VamsiSangam** [comment]
Seems to be working now [https://vamsisangam.github.io/opencodecollab/](https://vamsisangam.github.io/opencodecollab/) 😄

**Comment by agbilotia1998** [comment]
https://agbilotia1998.github.io/opencodecollab/

**Comment by Abhey** [comment]
https://abhey.github.io/opencodecollab/

**Comment by aswinzz** [comment]
https://aswinzz.github.io/opencodecollab/

**Comment by gauthamzz** [comment]
@aswinzz the gh pages should show the opencodecollab website 
i think you may have done something wrong

**Comment by pradeepgangwar** [comment]
Sir it's done... :)

https://pradeepgangwar.github.io/opencodecollab/

**Comment by aswinzz** [comment]
https://aswinzz.github.io/opencodecollab/
sir it's working now

**Comment by RavicharanN** [comment]
GH Pages link :  https://ravicharann.github.io/opencodecollab/

**Comment by Anupam-dagar** [comment]
Enabled gh-pages:
https://anupam-dagar.github.io/opencodecollab/

**Comment by sashank27** [comment]
https://sashank27.github.io/opencodecollab/

**Comment by tarunsinghal97** [comment]
https://github.com/tarunsinghal97/opencodecollab

**Comment by gauthamzz** [comment]
@tarunsinghal97 not working

**Comment by tarunsinghal97** [comment]
https://tarunsinghal97.github.io/opencodecollab/

**Comment by LuD1161** [comment]
Enabled gh pages

https://lud1161.github.io/opencodecollab/

**Comment by DreadedLama** [comment]
Enabled gh-pages :
https://dreadedlama.github.io/opencodecollab/

**Comment by gauthamzz** [comment]
@DreadedLama You need to first register first :) By adding yourself in the students section

**Comment by DreadedLama** [comment]
Done!! :)

**Comment by vsvipul555** [comment]
Enabled gh-pages on my fork.. !! Link- https://vsvipul555.github.io/opencodecollab/

**Comment by dabbler011** [comment]
enabled g-h pages:
https://dabbler011.github.io/opencodecollab/

**Comment by aswanthkoleri** [comment]
https://aswanthkoleri.github.io/opencodecollab/

**Comment by utkarshchaurasia28** [comment]
https://utkarshchaurasia28.github.io/opencodecollab/

**Comment by gauthamzz** [comment]
@utkarshchaurasia28 its not right, i think you need to enable gh pages on master branch . please fix that and comment

**Comment by Aotoge** [comment]
Enabled gh pages
[https://aotoge.github.io/opencodecollab/](url)

**Comment by Aotoge** [comment]
[https://aotoge.github.io/opencodecollab/](url)

**Comment by anu-007** [comment]
https://anu-007.github.io/opencodecollab/

**Comment by snipecoder1** [comment]
https://snipecoder1.github.io/opencodecollab/

**Comment by gauthamzz** [comment]
@everyone please add your score in _score.yml

**Comment by rahulsunny** [comment]
https://rahulsunny.github.io/opencodecollab/
