### ISSUE TITLE
Merge Opencode website with opencodecollab website

### ISSUE THREAD

**Issue by aswinzz** [fossiiita/opencode2017#181]
The webpage of opencode seems to be left out.
So it will be good if we merge it to opencodecollab website
Not Just Merging will do.
think of some idea of merging rather than linking the pages
this is my contribution to issue no #58

**Comment by gauthamzz** [comment]
please comment the effect you are going to put

**Comment by aswinzz** [comment]
http://codepen.io/wagerfield/pen/wftcE
is this okay?

**Comment by gauthamzz** [comment]
it looks awesome 
make this part of project page or make it a new page

**Comment by aswinzz** [comment]
ok

**Comment by aswinzz** [comment]
@RavicharanN  wishes to work on this issue
