### ISSUE TITLE
Add a countdown for opencode

### ISSUE THREAD

**Issue by aswinzz** [fossiiita/opencode2017#223]
It would be nice if we have a countdown timer for the ending of opencode

**Comment by Anupam-dagar** [comment]
I would like to work on it

**Comment by gauthamzz** [comment]
tell me if you face any problem

**Comment by Anupam-dagar** [comment]
Where shouls it be placed?

**Comment by gauthamzz** [comment]
before mentors in the index page

**Comment by Anupam-dagar** [comment]
![screenshot from 2017-02-15 22-51-24](https://cloud.githubusercontent.com/assets/21174572/22986377/4f5d26c0-f3d1-11e6-9b72-3c9bacbb42ac.png)
Is this fine?
I wanted it to be horizontal but it won't align.

**Comment by gauthamzz** [comment]
Too big

**Comment by Anupam-dagar** [comment]
![screenshot from 2017-02-16 14-04-17](https://cloud.githubusercontent.com/assets/21174572/23013492/d8e4d120-f450-11e6-83b1-f55e74084d25.png)
Is this fine?

**Comment by gauthamzz** [comment]
yeah it looks great make it a bit smaller and it will do

**Comment by Anupam-dagar** [comment]
![screenshot from 2017-02-17 18-10-14](https://cloud.githubusercontent.com/assets/21174572/23065599/62cb04fe-f53c-11e6-95ea-aa78f35e662c.png)
I think this should do it,its also bug free.

**Comment by gauthamzz** [comment]
LGTM send pr
