### ISSUE TITLE
write your experience in a blog

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#226]
write your opencode experience in a blog post. This is to be added in #225 . You can write the post in any blogging platform such as medium or even facebook post will work. 

As we are reaching the end we will take this as a review of the overall event.

**Comment by aswanthkoleri** [comment]
Should i post it in FB or post it in the blog which aswin is working on ?

**Comment by aswanthkoleri** [comment]
or both ?

**Comment by gauthamzz** [comment]
you need to add the link of your blog in the blog section @aswinzz is working on as well as share it
