### ISSUE TITLE
make everything respsonsive

### ISSUE THREAD

**Issue by aswinzz** [fossiiita/opencode2017#227]
in the image below we can see that the text is not completely in the black rectangle some part of the title is left out
![screenshot from 2017-02-15 14-54-00](https://cloud.githubusercontent.com/assets/25057819/22968025/d93a35a6-f38e-11e6-879a-4b6453f7fcef.png)

**Comment by gauthamzz** [comment]
there are so many others like this . the page is not responsive yet .

**Comment by agbilotia1998** [comment]
![responsive](https://cloud.githubusercontent.com/assets/21157929/22978157/99e71616-f3b7-11e6-90a3-dcc14593acbc.png)
Is it good now..

**Comment by gauthamzz** [comment]
yeah :) send pr
