### ISSUE TITLE
create javascript games 

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#278]
participants can create javascript games . they can comment them under this post.
when number of games increase we will set up a separate section for it

**Comment by RavicharanN** [comment]
It should be done by tomorrow right ?

**Comment by gauthamzz** [comment]
yeah

**Comment by aswanthkoleri** [comment]
I created a javascript game. A simple brick game. You can access it from this repo :  https://github.com/aswanthkoleri/MY-FIRST-JAVASCRIPTGAME
Thank You for this task

**Comment by gauthamzz** [comment]
Why thank you for this task

**Comment by aswanthkoleri** [comment]
I Learnt a lot of javascript thats why !!

**Comment by aswanthkoleri** [comment]
to play the game click here : https://aswanthkoleri.github.io/Brick-Pop/

**Comment by Anupam-dagar** [comment]
![screenshot from 2017-02-17 15-26-10](https://cloud.githubusercontent.com/assets/21174572/23060870/91483d18-f525-11e6-9694-e2ed2466997a.png)
As seen in github quick talk.
live link:
https://anupam-dagar.github.io/javascript-game/

**Comment by gauthamzz** [comment]
@adeora7 look at that

**Comment by adeora7** [comment]
:o oh man .. @gauthamzz  so happy to see that
