### ISSUE TITLE
Add your name in the students section

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#3]
Everyone is requested to add your name to the students section. Comment on this thread if you face any issue

Requirements:
- Name added in the students section
- A social media post or a tweet highlighting the changes you made along with the hashtags " #opencode #geekhaveniiita #iiita "

**Comment by VamsiSangam** [comment]
For the images, will a link do? [Example](https://avatars3.githubusercontent.com/u/11662001?v=3&s=240)

**Comment by gauthamzz** [comment]
No, you need to add images in the images/students , please create a students folder :+1:

**Comment by VamsiSangam** [comment]
Ok 😄

**Comment by mrsaicharan1** [comment]
Added profile to students.

**Comment by pradeepgangwar** [comment]
added profile and made pr.

**Comment by Anupam-dagar** [comment]
Added profile to students section.

**Comment by gauthamzz** [comment]
please post on social media to complete this step provide link here and refer you commit here

**Comment by Anupam-dagar** [comment]
Social media post link:
https://www.facebook.com/invincible.anupam/posts/1340712015973719

Commit:https://github.com/fossiiita/opencodecollab/pull/48

Anupam DagarIIT2016128@iiita.ac.in

**Comment by sashank27** [comment]
Added Profile to students.

**Comment by gauthamzz** [comment]
please post on social media with pic with link to event and complete this step @sashank27

**Comment by vsvipul555** [comment]
![capture](https://cloud.githubusercontent.com/assets/21038781/22109657/a661ba2a-de7e-11e6-83dc-5f3d0281d5d1.JPG)
Made social media post and added to students section.. !!

**Comment by LuD1161** [comment]
https://www.facebook.com/AseemShrey/posts/1733438650318337?notif_t=like&notif_id=1484998112566254

**Comment by gauthamzz** [comment]
@LuD1161 the link is not working

**Comment by LuD1161** [comment]
Check this one 

https://www.facebook.com/AseemShrey/posts/1733438650318337

**Comment by nikhilmundra29** [comment]
![capture](https://cloud.githubusercontent.com/assets/21039014/22176459/f3a3d53a-e030-11e6-9ee8-cd088053add2.PNG)

Made social media post and added to students section.. !!

**Comment by LuD1161** [comment]
@gauthamzz Did you check this one 

https://www.facebook.com/AseemShrey/posts/1733438650318337

**Comment by DreadedLama** [comment]
Done

https://www.facebook.com/permalink.php?story_fbid=428254057565864&id=100011438206757

**Comment by Aotoge** [comment]
Posted and added !

https://www.facebook.com/kadambari.kaveri/posts/1496855113688372
