### ISSUE TITLE
fix countdown.

### ISSUE THREAD

**Issue by Anupam-dagar** [fossiiita/opencode2017#320]
Countdown resets itself on refreshing the page.
It would be better if we can retain the count.

**Comment by VamsiSangam** [comment]
Could you explain what does [this line](https://github.com/fossiiita/opencodecollab/blob/master/javascripts/countdown.js#L41) in your code do?

`var deadline = new Date(Date.parse(new Date()) + 6 * 59 * 60 * 1000);`

**Comment by VamsiSangam** [comment]
Working on this...

**Comment by gauthamzz** [comment]
@VamsiSangam is assigned

**Comment by VamsiSangam** [comment]
It was a one line fix, not sure if this deserves 30 points 😄

**Comment by gauthamzz** [comment]
its okay :+1: last day let the points flow
