### ISSUE TITLE
Point System Show[discussion]

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#64]
We need to show all the points that a particular user has got in this repository.
Please suggest your way as the comment.

**Comment by pradeepgangwar** [comment]
what thing we can do to show points is that we can add points to flip cards where social links are shown.

What you all say about that.

**Comment by bhanu1911** [comment]
Adding them to the image as a translucent overlay on the cards, or as a part of the bio on the student page can work well, IMO.

**Comment by VamsiSangam** [comment]
As far as I am concerned, we can't calculate scores programmatically. It's too tedious and we don't have a way to programmatically get scores for comment based issues. That being said, here's my solution -

We need another attribute in ```students.yml```, let's say ```score```. Each individual student will submit a PR to edit his/her ```score``` attribute. In the description of the PR, the individual must give a link to the contribution (PR/issue comment) and mention the score added for each particular contribution. The mentors need to evaluate all the references (which shouldn't be difficult as links are given). If everything is okay, the PR will be merged. So we would have each students score stored away.

An example just to clarify things. If it were me, I would submit a single PR listing out my contributions so far. Example in my PR description -

1. [Added profile to students](https://github.com/fossiiita/opencodecollab/pull/7) +30
2. [Linked logo to main website](https://github.com/fossiiita/opencodecollab/pull/37) +20
3. [Projects section](https://github.com/fossiiita/opencodecollab/pull/40) +30
4. [Enable gh-pages on your fork](https://github.com/fossiiita/opencodecollab/issues/15#issuecomment-273281903) +30
..... Total = +200 (say)

And in my PR I would be editing my ```score``` attribute to whatever is the total mentioned in the PR description. This would be evaluated by mentors and merged if everything adds up properly.

And from then onwards, once a student makes a contribution, he/she can make a quick PR to update his/her score in the ```.yml``` file. Once we have the scores attribute going in ```students.yml```, we can figure out later how to display it in a fancy leaderboard.

**Note** - The student must strictly provide **hyperlinks** and not references (eg. #64) as this might make the issues very clumsy.

Pros -
* No actual programming to handle all cases needed.
* Maintained by students, so they get more experience using git. Lesser worries for mentors.
* Flexibility in using scores anyway we like once we get it into ```students.yml```

Cons -
* Initial setup is a little heavy.

This is my crude idea. You can refine it further. Please let me know your opinions. Thank you 😄

**Comment by gauthamzz** [comment]
@VamsiSangam its better to make a new file `score.yml` rather i think. 
I had thought of this but the con is too huge , I guess we can implement this.

**Comment by VamsiSangam** [comment]
Sure, but what would exactly go in the ```score.yml```?

**Comment by gauthamzz** [comment]
links of all the tasks completed and score of that task 
total at the end

**Comment by VamsiSangam** [comment]
Ok 👍 . Will PM you on gitter about this
