### ISSUE TITLE
General tasks 

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#87]
Comment your names after doing these talks 
1 social network share ( link needed )
2 join gitter channel
3 fork and star all opencode related projects in the website like opencode,opencodecollab , humblefool cup,Django event platform

**Comment by Ellusionists** [comment]
Ellusionists
1.(I share everything on facebook with the three hashtags.. which link do I provide?)
2. Done  3. Done

**Comment by Anupam-dagar** [comment]
Anupam Dagar
1.Social Media Link:
https://www.facebook.com/photo.php?fbid=1342957992415788&set=a.186619264716339.49725.100001048012821&type=3
2. Joined
3. Done.

**Comment by VamsiSangam** [comment]
Vamsi Sangam

1. [Facebook post](https://www.facebook.com/vamsi.sangam/posts/1312222565503468).
2. Joined
3. Stared & forked all 4 repos 😄

**Comment by aswinzz** [comment]
Aswin VB
1. [Facebook Post](https://www.facebook.com/photo.php?fbid=1176420729122246&set=a.165748876856108.33202.100002629918599&type=3&theater)
2. joined
3. Forked And Starred all Repos In fossiiita

**Comment by Symphoria** [comment]
Harshit Jain

1. [https://www.facebook.com/harshit.jain.37604303/posts/757481784402080?pnref=story](url)
2. Done
3. Done

**Comment by tarunsinghal97** [comment]
Tarun Singhal
1. https://www.facebook.com/tarun.singhal.148/posts/1046611225440741?pnref=story
2. Done
3. Done

**Comment by agbilotia1998** [comment]
Ayush Gupta

1. https://www.facebook.com/permalink.php?story_fbid=244359792672429&id=100012952303406&pnref=story
2. Done
3. Done

**Comment by aswanthkoleri** [comment]
1.[facebook post](https://www.facebook.com/photo.php?fbid=1439831206050177&set=a.285226671510642.77797.100000699350058&type=3&theater)
2.done 
3.done

**Comment by anu-007** [comment]
Anubhuti verma
1. https://www.facebook.com/anubhutiv1/posts/1183931645038260
2.done
3.done

**Comment by RavicharanN** [comment]
RavicharanN

1. Post:  
  https://www.facebook.com/photo.php?    fbid=1192397350836199&set=a.440067306069211.1073741827.100001978378442&type=3&theater
2. done 
3. Joined
