### ISSUE TITLE
Install on your system 

### ISSUE THREAD

**Issue by gauthamzz** [fossiiita/opencode2017#9]
Go through the README.md of the repository and build the website by jekyll on your local machine as instructed . This issue is open for everyone.

Requirements:
 - A screenshot in the issue
 - Make a social media post or a tweet, something in the lines  "Just installed jekyll and built the opencode website on my local System. Happy Contributing #opencode #geekhaveniiita #iiita" ( hashtags necessary )
visit https://fossiiita.github.io/opencode for more details

**Comment by bhanu1911** [comment]
Sir do we add the screenshots in the facebook post itself?

**Comment by gauthamzz** [comment]
@bhanu1911 you need to add screenshot here and facebook post also :+1:

**Comment by bhanu1911** [comment]
![screenshot from 2017-01-17 21-16-22](https://cloud.githubusercontent.com/assets/19773764/22032229/862bef6c-dd09-11e6-939b-87c05976189d.png)


Is this okay sir?

**Comment by Ellusionists** [comment]
![screenshot from 2017-01-18 00-26-38](https://cloud.githubusercontent.com/assets/21156892/22035256/4e47f080-dd15-11e6-92f5-c0b43eb1c36f.png)
Server's running all good. :)

**Comment by pradeepgangwar39** [comment]
Its done :)

![opencode](https://cloud.githubusercontent.com/assets/21259802/22038612/ed5af1ca-dd21-11e6-94f9-8ea98439ad7b.png)

**Comment by mrsaicharan1** [comment]
![image](https://cloud.githubusercontent.com/assets/25197147/22063317/3b6dc9d2-dda4-11e6-80f0-dffb45704374.png)

**Comment by gauthamzz** [comment]
@mrsaicharan1 i think you uploaded the wrong image

**Comment by mrsaicharan1** [comment]
I downloaded choclatey, the command shell variant .(it was an alternative installation method). Is it the wrong image.

**Comment by gauthamzz** [comment]
nah you have to post the image of it running on your browser :+1: running on localhost like everyone else :+1: @mrsaicharan1

**Comment by mrsaicharan1** [comment]
Okk sir

On Jan 18, 2017 5:49 PM, "Gautham Santhosh" <notifications@github.com>
wrote:

nah you have to post the image of it running on your browser 👍 running on
localhost like everyone else 👍 @mrsaicharan1
<https://github.com/mrsaicharan1>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fossiiita/opencodecollab/issues/9#issuecomment-273461249>,
or mute the thread

**Comment by Anupam-dagar** [comment]
Finally jekyll is set up and server is running fine.
![screenshot from 2017-01-18 15-02-57](https://cloud.githubusercontent.com/assets/21174572/22069195/6e807ac8-dd8f-11e6-9703-1af1637d046b.png)

**Comment by gauthamzz** [comment]
Please post your social media links with the image :+1:

**Comment by Anupam-dagar** [comment]
Social Media link:
Facebook:
https://www.facebook.com/photo.php?fbid=1340845235960397&set=a.186619264716339.49725.100001048012821&type=3
![screenshot from 2017-01-18 15-10-34](https://cloud.githubusercontent.com/assets/21174572/22069430/54524dec-dd90-11e6-95c3-43c3756747e0.png)
Twitter:
https://twitter.com/anupam_dagar/status/821737134407172097
![screenshot from 2017-01-18 15-13-50](https://cloud.githubusercontent.com/assets/21174572/22069556/c3c3edd4-dd90-11e6-8ec4-3faa54fdb04c.png)

**Comment by RavicharanN** [comment]
![screen shot 2017-01-20 at 1 48 19 am](https://cloud.githubusercontent.com/assets/22046387/22124402/b9f73628-deb5-11e6-94bc-dbaa31636f27.png)

Social Media link : 
https://www.facebook.com/photo.php?fbid=1192397350836199&set=a.440067306069211.1073741827.100001978378442&type=3&theater

**Comment by aswanthkoleri** [comment]
![deepinscreenshot20170120112711](https://cloud.githubusercontent.com/assets/21339090/22148021/aef70bd8-df03-11e6-8b3c-ca431464f911.png)

Social media link
Facebook : https://www.facebook.com/photo.php?fbid=1439831206050177&set=a.285226671510642.77797.100000699350058&type=3&theater

Twitter : https://twitter.com/aswanth9495/status/822408570474033152

**Comment by aswinzz** [comment]
Social Media Link
Facebook:https://www.facebook.com/photo.php?fbid=1176420729122246&set=a.165748876856108.33202.100002629918599&type=3&theater

twitter:https://twitter.com/aswinvb1/status/822686035486371841
![screenshot from 2017-01-21 11-30-36](https://cloud.githubusercontent.com/assets/25057819/22172471/aaec884a-dfcd-11e6-87b8-b5176c3aa368.png)

**Comment by Aotoge** [comment]
![opencode_love](https://cloud.githubusercontent.com/assets/22166269/22183007/57814ab2-e0d9-11e6-8db9-1ea2f15430f8.png)

Social Media Link(Facebook): [https://www.facebook.com/photo.php?fbid=1495479840492566&set=a.160289287344968.30895.100000916943110&type=3&theater](url)

**Comment by anu-007** [comment]
![screenshot from 2017-01-23 22-52-53](https://cloud.githubusercontent.com/assets/20153241/22214721/c3044182-e1be-11e6-80a6-d3f2c917a878.png)

**Comment by itaditya** [comment]
Screenshot : 
![image](https://cloud.githubusercontent.com/assets/15871340/22974799/04ef7362-f3aa-11e6-8ae7-25730547ef25.png)

**Comment by VamsiSangam** [comment]
![opencodecollab](https://cloud.githubusercontent.com/assets/11662001/23006376/620faa1c-f427-11e6-9dd0-396772280d96.JPG)
